[project]
name = "mcp-python-server"
version = "0.1.0"
description = "MCP server for searching official developer documentation"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]<2",
    "python-dotenv>=1.2.3",
    "trafilatura>=2.2.0",
]

[tool.uv]
package = false
